### ISSUE TITLE
Regarding the problems when running the map-sr

### ISSUE THREAD

**Issue by ko0000** [njaupan/ECDNA#2]
[error-2021-10-17_01-51-59.txt](https://github.com/njaupan/ecc_finder/files/7386432/error-2021-10-17_01-51-59.txt)
[ecc.sr.csv](https://github.com/njaupan/ecc_finder/files/7386434/ecc.sr.csv)

Hi Panpan, 

When I was running the map-sr, I encountered the following two problems. 

---I was trying to identify the eccDNA from my Illumina WGS data. However, some of my data couldn't go through the entire process (fail in the middle). All Illumina read data I used are in the same format and have undergone the same trimming process. 

---When I check the successful result, only 6 columns were showing in the output ecc.sr.csv. (see the attachment). I saw there are 7 cols in your example output. 

I attached the log file and the output csv, which may help you to identify the problem.

The script I ran is below : ("$link" is the folder name (for loop))

python ecc_finder.py map-sr /home/ik393/db/Arath/TAIR10_chr_all.fas /home/ik393/eccdna/"$link"/trimed_c_m_h.1.fq /home/ik393/eccdna/"$link"/trimed_c_m_h.2.fq -o ./"$link"_tair10/ -r /home/ik393/db/Arath/TAIR10_chr_all.fas 

Best, 

Ko

**Comment by njaupan** [comment]
Dear Ko,

Q1:  ecc_finder is degined for sequencing data with prior enrichment for circular DNA. Given any genomic (WGS) or ATAC-seq data, in its mapping mode, ecc_finder will output the bed file containing the numbers of split and discordant reads. However, the peak calling will not be effective because of the lack of enrichment. Therefore, I would suggest you to ONLY look at ecc.sr.split.num.bed and ecc.sr.disc.num.bed for WGS/ATAC-seq data.

Q2: It should be 6 columns in the output ecc.sr.csv. Thank you to point it out.

Best,
panpan

**Comment by ko0000** [comment]
Thank you!
